### ISSUE TITLE
Todo list?

### ISSUE THREAD

**Issue by rubyFeedback** [xu4-engine/u4#1]
Hey guys,

This is more a question, perhaps a small request.

Is there a document that:

a) shows the completion of the project compared to u4, e. g. what is playable what is not
b) shows a todo list of things that are missing or so?

In particular b) may perhaps be helpful in the long run when devs come in but may only
have a limited amount of time, so perhaps they could work on a todo list for some days
before moving on.

**Comment by WickedSmoke** [comment]
The TODO list is in the workshop: https://github.com/xu4-engine/workshop/blob/master/TODO

The Bugs section at the top lists what needs to be done before the next Beta release.
