### ISSUE TITLE
Tag for 1.1 ?

### ISSUE THREAD

**Issue by mausch** [xu4-engine/u4#10]
Hi, great news about the 1.1 release, congrats!
Could you tag it here on github so I can package it?
Many thanks.

**Comment by WickedSmoke** [comment]
Some documentation needs to be updated before I tag the release, so it may be another day or so.  What system are you packaging it for?

**Comment by mausch** [comment]
> What system are you packaging it for?

https://github.com/NixOS/nixpkgs

I have 1.0 already packaged [here](https://github.com/mausch/nixpkgs/commit/50ad3f962303bc4bf7c5f38b06f16a2f75ef7bd3), just need to clean it up and send a PR.

**Comment by WickedSmoke** [comment]
I've just updated the build instructions in my personal repo (https://github.com/WickedSmoke/xu4/blob/master/doc/build.md).

Note that the XML configuration is no longer supported and the Allegro audio libraries have been deprecated in favor of the new Faun library.

**Comment by WickedSmoke** [comment]
I created a release branch that will become v1.1.  The top level Makefile now has an "install" target so please try packaging that and let me know how it works out.

If you want a source archive for testing you can use this URL:
    https://github.com/xu4-engine/u4/archive/refs/heads/release.zip

**Comment by WickedSmoke** [comment]
Commit bb02ea4 has been tagged.
