### ISSUE TITLE
Cannot get Xu4 1.1 to run "Cannot find module"

### ISSUE THREAD

**Issue by Astaldo711** [xu4-engine/u4#11]
I unpacked the files to a folder named XU4. In this folder I have another folder named Ultima4. In this folder are all the game files I installed from gog. When I try to run xu4.exe, I get a message "Cannot find module Ultima IV".

**Comment by WickedSmoke** [comment]
This indicates that the game module declared in xu4.cfg cannot be found.  For v1.1 there should be a line like this:

    game=Ultima-IV

Earlier versions used a different name.  You can remove the xu4.cfg, erase that line, or set it as above.

**Comment by Astaldo711** [comment]
Thanks for the quick response. I don't seem to have a xu4.cfg file. I searched in appdata/local and also used explorer to search my PC.

**Comment by WickedSmoke** [comment]
The file would be in %AppData%.  If xu4.cfg does not exist then the Ultima-IV.mod will be used.  Since you report that the module name has a space and not a hypen I can only assume that there is an old config file being loaded.

**Comment by WickedSmoke** [comment]
The next version will have a --verbose message showing what settings file is being loaded.

**Comment by Astaldo711** [comment]
Got it working, thank you! Found the file in appdata/roaming
