### ISSUE TITLE
Cheat menu not working with cheats and enchancements on

### ISSUE THREAD

**Issue by dfgdgdgfd** [xu4-engine/u4#13]
It's like the game completely ignores the ctrl key.  It's working for everything else in windows.  E.g ctrl+h just causes me to Hole up and camp.

**Comment by WickedSmoke** [comment]
Cheating must be enabled in the configuration.  Is the "Enhanced Gameplay Options" -> "Debug Mode" set  to "On"?

**Comment by dfgdgdgfd** [comment]
I'm not seeing your response here for some reason, but yes it definitely is turned on.

**Comment by WickedSmoke** [comment]
What xu4 version and OS are you running?  Try running from the Command Prompt with "-v" and let me know what keycode is reported when you press Ctrl-C.

On my Windows box this is reported:

    key event: unicode = 99, sym = 3, mod = 2; translated = 3

**Comment by dfgdgdgfd** [comment]
I don't get any keycode reported, in the game or in the command prompt.  DR-9609c59f.  Windows 10 21h2.

**Comment by WickedSmoke** [comment]
Please try the v1.2.1 release and let me know if you get any output when using "-v".

**Comment by dfgdgdgfd** [comment]
Now I'm getting invalid settings file validate xml=1 and cannot find movule ultimaiv.  All the original ultima 4 files are in the same folder as xu4.  Same thing happening with the gog version.

**Comment by WickedSmoke** [comment]
Please remove or edit your xu4.cfg file.  See issue #11 for some details.

**Comment by dfgdgdgfd** [comment]
That did work, but now for some reason I have the original cga/ega graphics.

**Comment by WickedSmoke** [comment]
Graphics (and music) are now changed by selecting a game module.  The module browser is opened with the Escape key.
