### ISSUE TITLE
companions' names not visible in party window

### ISSUE THREAD

**Issue by bleedforever** [xu4-engine/u4#14]
![Screenshot from 2023-03-06 23-54-59](https://user-images.githubusercontent.com/81044636/223335408-b3081949-f80f-4ed1-a5ea-e889d902a821.png)
_the avatar at the top, dupre on the left, and jaana on the right. dupre's name is highlighted in the party window, but the text is invisible._

switching from `U4-Upgrade` to `Ultima-IV` then back to `U4-Upgrade` fixes the party window like 20% of the time. i'd try it with the vanilla graphics, but i can't play without the upgrade anymore -- when switching to `Ultima-IV` and attempting to load my save, xu4 crashes:
```
xu4: warning: Can't load image "u4/start.ega" with type 3
Segmentation fault (core dumped)
```

i started playing without the modded graphics and it seemed to work fine, but i only had a companion join after i'd installed the upgrade. now, even trying to start a new (non-upgraded) game (with a clean `~/.config/xu4/`, so default settings) crashes after the personality test -- everything works fine up to that point.

i'm using the gog release in a directory named `ultima4`, next to the xu4 binary and `u4upgrad.zip`. and i'm using pop!_os 22.04 lts (ubuntu) and the prebuilt xu4 1.2.1 release from sourceforge

**Comment by WickedSmoke** [comment]
The [Development Snapshots](https://xu4.sourceforge.net/download.php) have been updated with fixes for these bugs.  The version is DR-072f2674.  There was also another issue after changing modules where the combat map would be empty.

Thanks for the report.  When using the snapshot you could also give the U4-Recreated module a try.  I'm curious about what people think of the NPC voices.

**Comment by bleedforever** [comment]
oh!! apologies for the non-issue -- i skimmed the commits since 1.2.1 and somehow didn't see anything about it >___< this is all indeed fixed, thank you!

and thanks for the quick response! i'm trying u4-recreated now -- the tts quality is really surprisingly good! it actually took me talking to two npcs until i realized it was a tts, haha... definitely a big improvement over [the voices in the fm towns marty version of ultima vi](https://www.youtube.com/watch?v=5p_jMFU3gy8)!

(wow, joe the drunken fighter in britain actually hiccups rather than just saying "hic"..! that's fantastic)

**Comment by WickedSmoke** [comment]
Those were unknown bugs - I just quickly fixed them on my [personal repo](https://github.com/WickedSmoke/xu4) after your report.

Having never played the later Ultimas, I didn't know if they had voices.  Heh, the U6 voice of "Sahn-tray" was unexpected.  I've noted that the U4-Recreated pronunciation is incorrect, but I just may leave it as the official version seems weird.

Yes, there are a few lines that include sound effects.
