### ISSUE TITLE
[Feature request] Let us select multiple music modules

### ISSUE THREAD

**Issue by Redyn** [xu4-engine/u4#18]
Let us select multiple music modules at once and hand-pick which track from each to play.

For example, the player could enable the Aradindae and Hurin music modules at once and have the game use the Hurin tracks for Wanderer and Towns, along with the Aradindae tracks for the rest of the music.

Hope that was clear enough.

**Comment by WickedSmoke** [comment]
This level of configurability is intended to be handled within modules.  That is to say you'll have to create a music module with your own mix.

If you're a non-technical Windows user I could put together an archive with the required tools to make this easier.

**Comment by Redyn** [comment]
That would be really welcome.

**Comment by WickedSmoke** [comment]
Ok, an [xu4-mod-tools.zip](https://xu4.sourceforge.net/download/xu4-mod-tools.zip) archive has been created.  Download that, extract all the files, and follow the instructions in the ReadMe.txt file.  The jist of it is this:

 1. Replace the files in `U4-MyMusicMix/music` with the OGG files you desire.
 2. Run the `Pack-MyMusicMix.bat` batch file.  This can be done from the
    Command Prompt or via File Explorer by double clicking on its icon.

**Comment by WickedSmoke** [comment]
All the currently available OGG music is in the various repositories here on this GitHub project, but note that you will have to rename some of them to match what
`U4-MyMusicMix/config.b` expects.

**Comment by WickedSmoke** [comment]
Another way to use multiple selection would be to randomly change which module a track is played from occasionally (perhaps on map changes).  This would help alleviate the monotony of the rather short pieces. 

Since users have a way to create their own music modules and these can be changed easily during the game, this issue will be closed for now.

**Comment by Redyn** [comment]
Sorry about the late reply.

Just tried that packer and it works wonders. Thank you very much.
