### ISSUE TITLE
"Master is unstable"

### ISSUE THREAD

**Issue by romatthe** [xu4-engine/u4#4]
Hey there, nice to see that this fantastic project has moved to Github and some additional work is being done on it!

The project description says that "Master is unstable", so where should we build from if we want to build xu4 from source or package it? The Sourceforge home page offers beta builds which are ancient (and probably shouldn't use) and snapshot builds, but it's not clear what commits/tags these were build from.

Also, as a side-note, are there any fundamental differences between the Allegro and SDL builds? Which one is the recommended version? Are there any up or downsides to either of them?

Thanks!

**Comment by WickedSmoke** [comment]
The unstable note is on my personal repository (a backup of work in progress) 
and does not refer to the xu4-engine project master.  I tried being more 
verbose in the description, but github does not allow newlines there, so I 
kept it brief.

The repos. are still hosted on SourceForge, but Github is kept current.

If you want to run the latest use the Development Snapshot Builds, which were 
updated today.  The CLI -h option and the About menu in the program shows the 
Git commit of the build.

The new official builds use Allegro, which is needed for OpenGL rendering (work 
in progress) and the new module packages that use Boron for configuration.  The 
SDL version needs to be updated to SDL 2, but if you want to use CPU rendering 
and the XML configuration, it will work.
