### ISSUE TITLE
Building binaries directly in github

### ISSUE THREAD

**Issue by apenney** [xu4-engine/u4#6]
Hi!

Earlier today I was having a quiet day at work and thought "I wonder if xu4 works on macos".. one thing led to another and I started investigating what it would take to make binaries directly in github themselves.  Before I finish this work I wanted to check in and ask... would you take a PR that spits out binaries as releases automatically?

I was thinking:

* Linux builds (most straightforward)
* Try and cross-build from linux for windows (with msys2)
* Macos will take the most work (but they do have mac runners in github)

If this is a PR you'd take I may have some questions (I've been trying to make this work locally and I'm not 100% sure on the optimal setup for boron, etc).

And just to show roughly what linux looks like right now:

```
jobs:
  release-linux-amd64:
    name: release-linux-amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dependencies
      run: |
        sudo apt update
        sudo apt install -y liballegro5-dev libxml2 libxml2-dev

    - name: Install boron
      run: |
        rm -rf boron
        git clone --depth 1 git://git.code.sf.net/p/urlan/boron/code boron
        cd boron
        ./configure
        make
        sudo make install install-dev

    - name: Configure
      run: ./configure

    - name: Build
      run: make
```

That at least gets to a point it can compile xu4.

(Oh and separately I'll mention I had to modify image.h to change #include "image32.h" to "support/image32.h" and xu4.h to "support/notify.h" to get working compiles).  Anyway, I just wanted to pick your brain about the entire effort before I go on any further :)

**Comment by WickedSmoke** [comment]
Ashley,

The project does need someone to get the Mac build working.  The Linux & Windows builds are fully automated via the tools/cbuild script and I would like to avoid any dependencies on Github (or any server based build system).  I'm willing to make an exception for Mac as the project currently has no other way to build for that OS.  If you don't have access to a Mac yourself I'm not sure it will be worth the trouble, as Walter in issue #3 was able to build a binary (SDL version), but it did not open any window.  Some debugging on an actual system may be required.

I can post a bit later with some info. on how the current container based build system works, but the main things to study are:
-   Makefile snapshot rule
-   tools/cbuild
-   dist/Makefile

**Comment by WickedSmoke** [comment]
There is now a build document in [doc/build.md](https://github.com/xu4-engine/u4/blob/master/doc/build.md) to explain things.

**Comment by WickedSmoke** [comment]
The problem with the support/ path missing from includes does not occur on my Fedora 33 & Ubuntu 21.10 systems.  Please try again with the latest code and if it still fails let me know the commit, file being built, and OS version.
