### ISSUE TITLE
xu4: error: Unable to initialize Allegro

### ISSUE THREAD

**Issue by ghost** [xu4-engine/u4#9]
I'm getting a mystery-meat "Unable to initialize Allegro" launching the sourceforge binaries of xu4 1.0 on a Debian bullseye system with Allegro 5.2.6 installed.

Running `xu4 --verbose` is no more enlightening.

**Comment by WickedSmoke** [comment]
The program was built using Allegro 5.2.7 so you'll have to install the latest version.

The same error was generated on a Pop! OS 21.10 virtual machine, but upgrading to 5.2.7 via the ppa:allegro/5.2 repository fixes the issue.  I'm not sure where you can get the latest Allegro for Debian.

**Comment by ghost** [comment]
OK, that makes sense.
